server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
    connection-timeout: -1
    keep-alive-timeout: -1

spring:
  application:
    name: inlinedata
  datasource:
    url: jdbc:mariadb://localhost:3306/inlinedata?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: parksj11
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  upload:
    dir: /Users/batang/Developments/files/inlinedata
