spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/inlinedata?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mariadb://211.53.209.159:3306/inlinedata?useUnicode=true&characterEncoding=UTF-8
    #username: root
    #password: parksj11
    username: inlinedata
    password: parksj11#$
  jpa:
    properties:
      hibernate:
        format_sql: true

app:
  upload:
    dir: /Users/batang/Developments/files/inlinedata
  result-import:
    watch-dir: /Users/batang/Library/CloudStorage/OneDrive-개인/posting
    archive-dir: /Users/batang/Library/CloudStorage/OneDrive-개인/posting/archive
    error-dir: /Users/batang/Library/CloudStorage/OneDrive-개인/posting/error
    polling-interval-ms: 10000
    stable-wait-seconds: 15
