spring:
  datasource:
    url: jdbc:mariadb://${DB_ADDR:211.53.209.159}:3306/inlinedata?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:inlinedata}
    password: ${DB_PASSWORD:parksj11#$}

app:
  upload:
    dir: /data/inlinedata
